apiVersion: v1
kind: Service
metadata:
  name: api-clusterip
  namespace: mychat
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: mychat
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: mychat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
