apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mychat

resources:
  - ../../base

secretGenerator:
  - name: api-secrets
    envs:
      - .env

generatorOptions:
  disableNameSuffixHash: true
