k8s_yaml(kustomize('../overlays/local'))

docker_build(
    'api',
    '../../../services/api',
    target='dev-runner',
    live_update=[
        sync('../../../services/api/src', '/app/src'), # hot-reload only when source code changes (if other files change, rebuild image)
    ],
)

docker_build(
    'web',
    '../../../services/web',
    target='dev',
    live_update=[
        sync('../../../services/web/src', '/app/src'),
        sync('../../../services/web/public', '/app/public'),
    ],
)
