apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: api-secretstore
  namespace: mychat
spec:
  provider:
    gcpsm:
      projectID: mychat-478423
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: api-serviceaccount
