apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-secrets
  namespace: mychat
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: api-secretstore
    kind: SecretStore
  target:
    name: api-secrets
    creationPolicy: Owner
  data:
  - secretKey: OPENAI_API_KEY
    remoteRef:
      key: OPENAI_API_KEY
  # add additional secrets here as needed
