apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mychat

resources:
  - namespace.yaml

  # API
  - api/configmap.yaml
  - api/deployment.yaml
  - api/service.yaml

  # Gateway
  - gateway/gateway.yaml
  - gateway/httproute.yaml

  # Web
  - web/deployment.yaml
  - web/service.yaml
