apiVersion: v1
kind: Service
metadata:
  name: web-clusterip
  namespace: mychat
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: mychat
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: mychat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
